### ISSUE TITLE
clojure.lang.ExceptionInfo: :auto not supported on headerless data. {}

### ISSUE THREAD

**Issue by bcotton** [Netflix/PigPen#168]
PigPen Version: 0.3.1-20150825.165235-4
java version: 1.7
hadoop version 2.4.0
java version: 1.7
pig versions: 0.12.0
AMI version:3.4.0
Hadoop distribution:Amazon 2.4.0

At the end of our map step we are seeing the following exception: 

Caused by: clojure.lang.ExceptionInfo: :auto not supported on headerless data. {}
	at clojure.core$ex_info.invoke(core.clj:4403)
	at taoensso.nippy$get_auto_compressor.invoke(nippy.clj:558)
	at taoensso.nippy$thaw$thaw_data__10665.invoke(nippy.clj:599)
	at taoensso.nippy$thaw.doInvoke(nippy.clj:644)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at pigpen.pig.runtime$fn__12071.invoke(runtime.clj:108)
	at pigpen.runtime$fn__2746$G__2741__2751.invoke(runtime.clj:186)
	at clojure.core$mapv$fn__6311.invoke(core.clj:6353)
	at clojure.core.protocols$fn__6074.invoke(protocols.clj:79)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at clojure.core$mapv.invoke(core.clj:6353)
	at pigpen.pig.runtime$fn__12069.invoke(runtime.clj:111)
	at pigpen.runtime$fn__2746$G__2741__2751.invoke(runtime.clj:186)
	at clojure.core$map$fn__4245.invoke(core.clj:2559)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$mapcat.doInvoke(core.clj:2586)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at pigpen.pig.runtime$fn__12067.invoke(runtime.clj:115)
	at pigpen.runtime$fn__2746$G__2741__2751.invoke(runtime.clj:186)
	at pigpen.pig.runtime$exec_initial.invoke(runtime.clj:295)
	at pigpen.pig.runtime$udf_algebraic.invoke(runtime.clj:337)
	at clojure.lang.Var.invoke(Var.java:388)
	at pigpen.PigPenFnAlgebraic$Initial.exec(PigPenFnAlgebraic.java:104)
	at pigpen.PigPenFnAlgebraic$Initial.exec(PigPenFnAlgebraic.java:88)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:330)

The map phase get to %100 and all the inputs seem to be processed.

Could it be some compression library thats not installed?

Any ideas where to look?

Thanks 
-Bob

**Comment by mbossenbroek** [comment]
It should be using nippy 2.8.0, which on my machine pulls in these dependencies (via `pigpen/pigpen-core$ ../gradlew dependencies`):

```
+--- com.taoensso:nippy:2.8.0
|    +--- org.clojure:clojure:1.4.0 -> 1.6.0
|    +--- org.clojure:tools.reader:0.8.13
|    |    \--- org.clojure:clojure:1.4.0 -> 1.6.0
|    +--- com.taoensso:encore:1.21.0
|    |    +--- org.clojure:clojure:1.4.0 -> 1.6.0
|    |    \--- org.clojure:tools.reader:0.8.13 (*)
|    +--- org.iq80.snappy:snappy:0.3
|    +--- org.tukaani:xz:1.5
|    \--- net.jpountz.lz4:lz4:1.3
```

I noticed that you're using a different pigpen build than is in maven - could it be pulling in something different? Are you able to confirm that these are what end up in the uberjar?

**Comment by bcotton** [comment]
lein deps :tree 
 [com.netflix.pigpen/pigpen-pig "0.3.1-20150825.165235-4"]
   [com.netflix.pigpen/pigpen-hadoop "0.3.1-20150825.165235-4" :scope "runtime"]
   [com.netflix.pigpen/pigpen "0.3.1-20150825.165235-4" :scope "runtime"]
     [com.taoensso/nippy "2.8.0"]
       [com.taoensso/encore "1.21.0"]
       [net.jpountz.lz4/lz4 "1.3"]
       [org.iq80.snappy/snappy "0.3"]
       [org.tukaani/xz "1.5"]

and the project.clj in the uberjar:
(defproject com.taoensso/nippy "2.8.0"
...

**Comment by mbossenbroek** [comment]
@ptaoussanis Any idea what would cause that error?

Bob, did this work previously? Did something change or is this a new setup?

**Comment by bcotton** [comment]
This is a new job, running in the same project/environment/cluster as other working jobs.

What is the root cause here? No data being passed to the reducers?

**Comment by mbossenbroek** [comment]
We use nippy (https://github.com/ptaoussanis/nippy) to serialize (freeze) and deserialize (thaw) data when interacting with the host environment. From the stack trace, this looks like it's at the beginning of a UDF call where it's deserializing the data for processing by your Clojure code.

The headerless bit in the error refers to the options we use to serialize the data. The default is to include a small header at the beginning of the serialized blob that documents what compressor was used, and other information that can inform deserialization later. We chose to disable this option because a few bytes per record adds up to a lot when you're processing billions of records. So far we haven't seen any issues as a result of this.

My interpretation of the error is that it can't figure out how to decompress the data because it doesn't have this header. Why this doesn't occur every time has me scratching my head. I would speculate that it's a specific piece of data you have that's hitting some edge case in the deserialization. Are you able to isolate a piece of data that causes this? Can you reproduce locally, or does this only happen in the cluster?

As a first step, we might want to try upgrading nippy to the latest release (2.9.1) & see if that fixes this issue. After that, there's likely a way to explicitly set the compressor/decompressor it's using so it doesn't have to figure it out automatically. This might be a good thing to do regardless as it will likely be faster.

**Comment by ptaoussanis** [comment]
> @ptaoussanis Any idea what would cause that error?

Hi Matt, your interpretation is correct. This error implies that:
1. `nippy/thaw` is being called with a `{:compressor :auto}` option (**the default**)
2. The data being thawed was written _without_ a Nippy header

So `thaw` is being asked to auto-detect the compressor used by examining the header, but there's no header to examine - so it's throwing.

If PigPen writes data without a header (something I'd recommend against, details later) - then (1.) above seems like the culprit: you'd need to track down where that `thaw` call's occurring.

Some points that may help with debugging:

> Why this doesn't occur every time has me scratching my head. I would speculate that it's a specific piece of data you have that's hitting some edge case in the deserialization.

If the intention is that `thaw` **never** be called with `{:compressor :auto}`, then I'd definitely be inclined to rule out these kinds of edge cases. The only place this error can be generated is here: https://github.com/ptaoussanis/nippy/blob/38efea3ca9c2d56a281cc9644cd21e90d8e8630e/src/taoensso/nippy.clj#L558

And the only consumer of that function is here:
https://github.com/ptaoussanis/nippy/blob/38efea3ca9c2d56a281cc9644cd21e90d8e8630e/src/taoensso/nippy.clj#L599

I.e. the *only* way this path gets triggered is by the presence of an `:auto`-compressor `thaw` call. No data is examined to produce this error.

> After that, there's likely a way to explicitly set the compressor/decompressor it's using so it doesn't have to figure it out automatically.

If you're serializing without the header, then you *must* be setting `thaw`'s `{:compressor _}` option to the compressor that was used for serialization.

----

# Re: disabling the error

I'd generally recommend against this in production systems. The cost of the header is 4 bytes per `freeze` call, and a small hit to performance. In exchange you get:

- A degree of protection against data corruption or use against unintentional data (via header integrity check)
- Protection against any breaking changes in Nippy version data formats (esp. nb between different servers that may be running different versions of Nippy)
- Support for the `:auto` compressor and encryptor `thaw` options (the default) - i.e. no need to worry about setting the right options
- Support for the `:auto` freeze compressor

That last one (new in Nippy v2.9+) allows Nippy to intelligently select a compressor best suited to each `freeze` call. For example, if it's a very small value - you'll often get better performance + space use by _not_ using any compressor. Use of this feature requires the header since the per-payload compressor info needs to be available during thawing.

You might find that with v2.9+ the header (and default `:auto`) options actually lead to the smallest possible (or near to the smallest possible) serialized sized in practice.

**Comment by mbossenbroek** [comment]
Thanks for the info! I'm definitely interested in trying out the new stuff in 2.9+ - it seems optimized towards the sort of work we're doing. Generally, the use case we see is serializing millions to billions of tiny values, often a single long or small maps or vectors.

While we start testing that, I am still curious how our current setup works. Below is the single call we make to serialize data, and we're using `thaw` with no arguments. Does it have to do with the `:legacy-mode` argument? IIRC, you advised using that at the time, but I don't recall why.

```clj
(freeze value {:skip-header? true, :legacy-mode true})
```
https://github.com/Netflix/PigPen/blob/29521576969b4cf4f1556e12300e5d2e10b9f012/pigpen-pig/src/main/clojure/pigpen/pig/runtime.clj#L64

https://github.com/Netflix/PigPen/blob/29521576969b4cf4f1556e12300e5d2e10b9f012/pigpen-pig/src/main/clojure/pigpen/pig/runtime.clj#L108


Bob, I should be able to get a snapshot build out later today to start testing this. The change should be relatively straightforward - just changing the nippy version & dropping those options.

**Comment by mbossenbroek** [comment]
Version 0.3.1-SNAPSHOT has been released to jfrog: https://oss.jfrog.org/oss-snapshot-local/com/netflix/pigpen/pigpen/0.3.1-SNAPSHOT/

Bob, could you try this version out & let me know if that resolves your issue? We're going to do some perf testing on our production jobs before releasing this.

**Comment by ptaoussanis** [comment]
> I'm definitely interested in trying out the new stuff in 2.9+ - it seems optimized towards the sort of work we're doing.

Sure, I'd suggest testing first (perhaps also against `2.10.0-RC1` out of curiosity) - but my guess would be that you'd see better or similar perf with v2.9+ and headers enabled.

> While we start testing that, I am still curious how our current setup works. Below is the single call we make to serialize data, and we're using thaw with no arguments.

`:legacy-mode?` I'd avoid unless you're looking to produce serialized output readable by legacy versions of Nippy (v1.x).

Note that if you're serializing with
```clojure
(freeze value {:skip-header? true, :legacy-mode true})
```

Then you **must** deserialize with
```clojure
(thaw bytes {:compressor snappy-compressor})
```

If you're currently just calling `thaw` w/o any options, that'd explain the reported error.

Let me recommend some alternative calls:
```clojure
;;; For Nippy v2.8.0, if you want to continue skipping headers for performance
(nippy/freeze val  {:compressor nippy/lz4-compressor :skip-header? true})
(nippy/thaw  bytes {:compressor nippy/lz4-compressor})

;;; For Nippy v2.9+ (incl. v2.10)
(freeze val)   ; Auto-select compressor
(thaw   bytes) ; Auto-select compressor
```

**Comment by bcotton** [comment]
Using 0.3.1-20150925.170336-5 resolved our issue.

Thanks!

**Comment by mbossenbroek** [comment]
Were you able to get a read on any performance difference? Any better or worse?

**Comment by bcotton** [comment]
Sample size of 1, using a 6 node AWS EMR cluster reading from S3.

252 min original
272 min after this change

~8% slower

**Comment by ptaoussanis** [comment]
> Sample size of 1, using a 6 node AWS EMR cluster reading from S3.
>
> 252 min original
> 272 min after this change
>
> ~8% slower

I've submitted a new PR at #170 which retains the header but drops all compression (the likely cause of any performance regression).

Do you need support for Clojure 1.4?

**Comment by mbossenbroek** [comment]
Thanks Peter! I'm interested in seeing the result of that change (we'll test it out too), but we really don't need the versioning stability. The serialization is there to transport intermediate products between machines that are all running identical code. It's never used to read user inputs or write the final product and will never last outside of a single job. That's why I felt so comfortable omitting the header.

We'll test out the following variants on our end with 2.9.1:

```clj
;; with header, auto compressor
(nippy/freeze val)
(nippy/thaw  bytes)

;; with header, no compressor
(nippy/freeze val  {:compressor nil})
(nippy/thaw  bytes)

;; no header, with compressor
(nippy/freeze val  {:compressor nippy/lz4-compressor :skip-header? true})
(nippy/thaw  bytes {:compressor nippy/lz4-compressor :encryptor nil})

;; no header, no compressor
(nippy/freeze val  {:compressor nil :skip-header? true})
(nippy/thaw  bytes {:compressor nil :encryptor nil})
```

@bcotton Do you have any appetite in doing side-by-side comparisons with your jobs? We would appreciate any feedback on which of these works better for you.


> Do you need support for Clojure 1.4?

Nope, pigpen requires Clojure >= 1.5.1

**Comment by ptaoussanis** [comment]
> We'll test out the following variants on our end with 2.9.1

Okay, hold up for a sec - let's try confirm some details before choosing tests to run.

Some questions:

* There's **zero** possibility that two freeze/thaw endpoints with different versions of Nippy will _ever_ share data? E.g. no data is ever retained (persisted to disk, etc.) for thawing at a later time under a possibly different system?
* You mentioned that a lot of your data is a single long or small maps/vectors. Could you give me an idea what you mean by "small" here? 2 elements? 100? [1]
* Is space efficiency any concern? I.e. would you ever be happy to pay for space efficiency with speed? Under what circumstances? [2]
* Any idea what your approximate average payload size is, in bytes?
* Any idea what the variance might be like? Or otherwise approximate upper/lower size limits? [3]
* Do all of your freeze/thaw endpoints definitely run the JVM in `-server` mode?

**Comment by mbossenbroek** [comment]
> * There's zero possibility that two freeze/thaw endpoints with different versions of Nippy will ever share data? E.g. no data is ever retained (persisted to disk, etc.) for thawing at a later time under a possibly different system?

That's correct - it's all used for intermediate products in a single hadoop job. All machines have identical copies of the jars and the frozen data is ephemeral. The serialization is only for moving data from one machine to the next.

> * You mentioned that a lot of your data is a single long or small maps/vectors. Could you give me an idea what you mean by "small" here? 2 elements? 100?

It really depends on the job; some of our jobs traffic in maps of a few dozen elements, a lot of them have maps of just a handful of elements. When joining data, we select a join key from each of these maps, which may be a single primitive value or a vector of 2-4 elements. More commonly we'll see fewer elements here. I would say that most of the time we're using stuff that ends up backed by array-based persistent storage in Clojure, but we wouldn't want a penalty for using larger maps.

These two cases are separate places in the code though - if there's a better method for primitives & small vectors and a different ideal config for small to large maps, we could in theory use different techniques there. That would be a much bigger change though - right now everything flows through a single method.

> * Is space efficiency any concern? I.e. would you ever be happy to pay for space efficiency with speed? Under what circumstances?

Potentially, but only because larger data takes longer to move between machines. Older hadoop setups will have one machine serialize the data, write it to disk, another machine reads it, and then deserializes it. Newer stuff will serialize & send over the wire to the next machine (I think - don't quote me on that).  If it takes longer to compress the data than it would just to move it, then it's not worth it. This is simply to transport data from one machine to the next as quickly as possible.

> * Any idea what your approximate average payload size is, in bytes?
> * Any idea what the variance might be like? Or otherwise approximate upper/lower size limits?

It can vary dramatically, depending on what data the user is processing. For our use cases, it will generally be 10's-100's of bytes, maybe a kb or two on the upper limit. I generally will be more liberal with the size of the record if I have fewer of them to work with. Anything under a million, I don't even consider the data size. When I know the source data has over a billion records, then I start thinking about making each record a small vector instead of a map.

> * Do all of your freeze/thaw endpoints definitely run the JVM in -server mode?

That's a great question - I'm not sure. @bcotton - do you know if hadoop always runs the JVM in server mode? I would be surprised if it didn't, but I can confirm that if Bob doesn't know offhand.

> * One last question: do you ever send the frozen data over a slow connection (e.g. non-local network) as part of job processing?

It should all be within a single datacenter or aws region. I don't know that I've ever heard of a hadoop cluster that's more spread out (which seems like a terrible idea).


So it sounds like you've got some ideas that could refine which variants to test (or just tell us the right answer)? Looking forward to what you come up with - thanks for the help on this!

**Comment by ptaoussanis** [comment]
> These two cases are separate places in the code though - if there's a better method for primitives & small vectors and a different ideal config for small to large maps, we could in theory use different techniques there. 

That shouldn't be necessary. Reason for asking: the most important knob here is compression - if, when, and how.

Nippy v2.9+ lets you dynamically select a compression method as a fn of the bytes being serialized (e.g. serialized data size). You don't seem to have a significant enough variation in data sizes to make this worth while though, so just disabling compression would likely be the right choice if performance is the priority.

> Potentially, but only because larger data takes longer to move between machines.

This might be worth testing, but I suspect the cost of compression here would easily outweigh any benefits. The uncompressed format is already lean - so we're talking about saving <~5% data size at an increased ~20% roundtrip time for LZ4.

> It can vary dramatically, depending on what data the user is processing. For our use cases, it will generally be 10's-100's of bytes, maybe a kb or two on the upper limit.

Okay, that's helpful - thanks.

> So it sounds like you've got some ideas that could refine which variants to test (or just tell us the right answer)? Looking forward to what you come up with - thanks for the help on this!

No problem - will update the PR in a few mins with suggestions.
